Now Evaluating
Evaluating for 50 steps
Traceback (most recent call last):
  File "/home/ec2-user/attribute_probe/clip_src/training_scripts/CLIP_image/eval_clip_image.py", line 202, in <module>
    evaluator.evaluate()
  File "/home/ec2-user/attribute_probe/clip_src/training_scripts/evaluator.py", line 44, in evaluate
    loss = self.validation_step(val_data, self.model, self.val_metrics, val_steps, log = True, wandb = self.wandb, args = self.args)
  File "/home/ec2-user/attribute_probe/clip_src/training_scripts/CLIP_image/eval_clip_image.py", line 104, in validation_step
    logger(metrics, step, wandb = wandb, train = False, args = args)
  File "/home/ec2-user/attribute_probe/clip_src/training_scripts/logger.py", line 10, in log_metrics
    metrics['Accuracy'] = metrics['Accuracy'] / metrics['class_total']
KeyError: 'class_total'