Traceback (most recent call last):
  File "/home/ec2-user/attribute_probe/clip_src/training_scripts/CLIP_image/eval_clip_image.py", line 174, in <module>
    checkpoint = torch.load('{name}'.format(name = args.saved_path))
  File "/opt/conda/envs/pytorch/lib/python3.9/site-packages/torch/serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/opt/conda/envs/pytorch/lib/python3.9/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/opt/conda/envs/pytorch/lib/python3.9/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'checkpoints/CLIP_image/CLIP_image_Final.pt'